/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 magnifier.gltf --transform
Author: Alexander (https://sketchfab.com/pravdin)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/magnifying-glass-3d-apple-emoji-c42c2a14d34244f2b3712c09c94befd7
Title: Magnifying Glass (3D Apple Emoji)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/magnifier-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.01, -0.03]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['Material.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/magnifier-transformed.glb')
